
import os
import io
import context
import task6
import pytest


# Counts provided by pasting into Microsoft Word
def test_count_words():
  context.reset()
  assert task6.count_words('rsc/task6_textfiles/Lorem Ipsum_104.txt') == 104



### META TESTS

# Move the CWD back to the test area
context.reset()
TEST_FILES_DIR = "rsc/task6_textfiles"


# metaprogramming function to generate one function per test text file in the TEST_FILES_DIR
# The test text files were generated by ChatGPT
def generate_test_function(file):
  def test_function():
    # Build the final path of the file
    file_path = os.path.join(TEST_FILES_DIR, file)
    # Parse the filename to extract the integer at the end of its name
    # This number was determined by letting Microsoft Word count the words in it
    # Then use this number as part of the assertion
    c = int('.'.join(file_path.split('.')[:-1]).split('_')[-1])
    assert task6.count_words(file_path) == c
  return test_function


# Go through the files in the TEST_FILES_DIR. Generate one test function
# per file ending with the ".txt" function.
ext = ".txt"
for file_name in os.listdir(TEST_FILES_DIR):
  if file_name.endswith(ext):
    test_name = f"test_count_{file_name[:-len(ext)].replace(' ', '_')}"
    globals()[test_name] = generate_test_function(file_name)

