# Generated by Django 4.2.19 on 2025-03-05 07:44

from bookings.models.seat import Seat
from django.db import migrations


def create_seats(apps, schema_editor):
    Seat.objects.create(title="The Shawshank Redemption", duration="142", release_date="1994-09-13", description="A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.")
    Seat.objects.create(title="The Godfather", duration="175", release_date="1972-03-14", description="The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.")
    Seat.objects.create(title="The Dark Knight", duration="152", release_date="2008-07-14", description="When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.")
    Seat.objects.create(title="The Lord of the Rings: The Return of the King", duration="201", release_date="2003-12-01", description="Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.")


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_preload_movies"),
    ]

    operations = [
        migrations.RunPython(create_seats)
    ]

